[package]
name = "ata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
umya-spreadsheet = "0.8"
chrono = "0.4"
log = "0.4"
flexi_logger = "0.23"
